source 'https://rubygems.org'
gem 'rack'
gem 'sinatra'
gem 'activesupport'
gem 'pg'
gem 'activerecord'
gem 'sinatra-activerecord'
gem 'tux'
gem 'shotgun'
gem 'rake'
gem 'pry'
gem 'faker'
gem 'require_all'
gem 'victor'
group :test do
 gem 'capybara'
 gem 'database_cleaner'
 gem 'rspec'
 gem 'rack-test'
end